---
title: "Arizona Map"
author: "Jose Dias"
date: "1/19/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Packgaes
```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)


library(tidyverse)
library(ggplot2)
library(knitr)
library(kableExtra)
library(scales)
library(ggthemes)
library(usmap)
library(ggsn)
library(ggmap)
library(ggrepel)
library(maps)
library(grid)
library(mapdata)
library(maptools)
library(stringr)
library(dplyr)
library(choroplethr)

```

```{r cars}
summary(cars)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)

# load the package
library("tidyverse")
library("ggplot2")

library(usmap)
library(ggplot2)

plot_usmap(regions = "counties") + 
  labs(title = "US Counties",
       subtitle = "This is a blank map of the counties of the United States.") + 
  theme(panel.background = element_rect(color = "black", fill = "lightblue"))

# Plot only certain states
library(usmap)
library(ggplot2)

plot_usmap(regions = "counties", include = c("AZ")) +
  labs(title = "Arizona",
       subtitle = "These are the states in the Pacific Timezone.")


#Add some data to the map
library(usmap)
library(ggplot2)

plot_usmap(regions = "counties", include = c("AZ"), data = statepop, values = "pop_2015", color = "red") + 
  scale_fill_continuous(name = "Population (2015)", label = scales::comma) + 
  theme(legend.position = "right")


devtools::install_github(“UrbanInstitute/urbnmapr”)

































```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
